#DATABASE_POOLER_URL: postgres://postgres.duayghzkcbwbxrhahvwn:tNxBPldqojwqw6b6@fly-0-atl.pooler.supabase.com:6543/postgres
#
#DATABASE_URL: postgres://postgres:tNxBPldqojwqw6b6@db.duayghzkcbwbxrhahvwn.supabase.co:5432/postgres?sslmode=require
server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: servicemaids

  datasource:
#    url: jdbc:postgresql://localhost:5432/togoisperf
    #togoisperf_usr
    #t0g015P3R
    username: postgres
    password: tNxBPldqojwqw6b6
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Configuración de HikariCP para conexiones
      schema: "servicemaids"
    url: jdbc:postgresql://db.duayghzkcbwbxrhahvwn.supabase.co:5432/postgres?sslmode=require

  jpa:
    hibernate:
      ddl-auto: update  # Opciones: validate, update, create, create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: servicemaids

  flyway:
    enabled: true
    locations: classpath:db/migration  # Migraciones con Flyway
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html  # URL de Swagger UI

logging:
  level:
    root: INFO
    com.com.servicemaids: DEBUG  # Logs detallados solo para tus clases
  file:
    name: logs/miaplicacion.log  # Archivo de logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Formato de logs en consola

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exponer todos los endpoints de monitoreo
  endpoint:
    health:
      show-details: always  # Mostrar detalles completos del estado
