server:
  port: 8080
spring:
  application:
    name: servicemaids
  datasource:
    url: jdbc:postgresql://localhost:5432/togoisperf
    username: togoisperf_usr
    password: t0g015P3R
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  # Configuración de HikariCP para conexiones
      schema: "gleamingnest"

  jpa:
    hibernate:
      ddl-auto: update  # Opciones: validate, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration  # Migraciones con Flyway
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html  # URL de Swagger UI

logging:
  level:
    root: INFO
    com.miapp: DEBUG  # Logs detallados solo para tus clases
  file:
    name: logs/miaplicacion.log  # Archivo de logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Formato de logs en consola

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exponer todos los endpoints de monitoreo
  endpoint:
    health:
      show-details: always  # Mostrar detalles completos del estado
